baseURL                = "https://example.com/"
defaultContentLanguage = "en"
title                  = "Hugo Forum Topic"
theme                  = "hugo"
disableKinds           = ['RSS', 'sitemap', 'taxonomy', 'term']

[build]
   [build.buildStats]
      enable = true
   [[build.cachebusters]]
      source = 'layouts/.*'
      target = 'css'
   [[build.cachebusters]]
      source = './tailwind.config.js'
      target = 'css'
